apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-platform-config
  namespace: bc-edge-apps
data:
  NEXT_PUBLIC_CONTRACT_ADDRESS: "0x8c0c3B8f93d627519E7C2451e52B834Ae240598a"
  NEXT_PUBLIC_BESU_RPC_URL: "http://172.27.3.58:30425"
  NEXT_PUBLIC_BESU_WS_URL: "ws://172.27.3.58:32575"
  NEXT_PUBLIC_BESU_CHAIN_ID: "1337"
  NEXT_PUBLIC_BESU_CHAIN_NAME: "Besu Network"
