apiVersion: v1
kind: Service
metadata:
  name: voting-platform-service
  namespace: bc-edge-apps
  labels:
    app: voting-platform-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30081
      protocol: TCP
      name: http
  selector:
    app: voting-platform
